import { useEffect, useState } from "react";
import "./App.css";

import { useImageAnalysis } from "./hooks/useImageAnalysis";

import AnalysisLoader from "./components/analysis/AnalysisLoader";
import VerdictCard from "./components/analysis/VerdictCard";

import UploadZone from "./components/upload/UploadZone";
import ImagePreview from "./components/upload/ImagePreview";

import { validateImageFile } from "./utils/fileValidation";

function App() {
  const [selectedFile, setSelectedFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [error, setError] = useState("");

  const {
    loading,
    result,
    error: analysisError,
    analyzeImage,
    resetAnalysis,
  } = useImageAnalysis();

  // ---------------------------------------------------------
  // HANDLE FILE SELECTION
  // ---------------------------------------------------------

  const handleFileSelected = (file) => {
    setError("");

    // Validate selected file
    const validation = validateImageFile(file);

    if (!validation.valid) {
      setSelectedFile(null);
      setPreviewUrl(null);
      setError(validation.error);
      return;
    }

    // Store selected file
    setSelectedFile(file);

    // Create preview URL
    const url = URL.createObjectURL(file);
    setPreviewUrl(url);

    // Reset any previous analysis
    resetAnalysis();
  };

  // ---------------------------------------------------------
  // REMOVE SELECTED IMAGE
  // ---------------------------------------------------------

  const handleRemove = () => {
    setSelectedFile(null);
    setPreviewUrl(null);
    setError("");

    resetAnalysis();
  };

  // ---------------------------------------------------------
  // CLEAN UP PREVIEW URL
  // ---------------------------------------------------------

  useEffect(() => {
    return () => {
      if (previewUrl) {
        URL.revokeObjectURL(previewUrl);
      }
    };
  }, [previewUrl]);

  // ---------------------------------------------------------
  // UI
  // ---------------------------------------------------------

  return (
    <div className="app">
      {/* =====================================================
          NAVBAR
          ===================================================== */}

      <header className="navbar">
        <div className="brand">
          <div className="brand-icon">AI</div>

          <div>
            <h1>AI Image Forensics</h1>
            <p>Zero-Shot Image Detection</p>
          </div>
        </div>

        <nav className="nav-links">
          <a href="#how-it-works">How It Works</a>
          <a href="#about">About</a>
        </nav>
      </header>

      {/* =====================================================
          MAIN CONTENT
          ===================================================== */}

      <main>
        {/* ===================================================
            HERO / ANALYSIS SECTION
            =================================================== */}

        <section className="hero">
          <div className="hero-content">
            <span className="eyebrow">
              ZERO-SHOT AI IMAGE DETECTION
            </span>

            <h2>
              Is this image
              <span> AI-generated?</span>
            </h2>

            <p className="hero-description">
              Analyze images for patterns associated with
              synthetic content — including images generated by
              models that were never seen during training.
            </p>

            {/* =================================================
                UPLOAD / PREVIEW
                ================================================= */}

            {!selectedFile ? (
              <UploadZone
                onFileSelected={handleFileSelected}
              />
            ) : (
              <ImagePreview
                file={selectedFile}
                previewUrl={previewUrl}
                onRemove={handleRemove}
              />
            )}

            {/* =================================================
                FILE VALIDATION ERROR
                ================================================= */}

            {error && (
              <div className="upload-error">
                {error}
              </div>
            )}

            {/* =================================================
                ANALYSIS SECTION
                ================================================= */}

            {selectedFile && (
              <>
                {/* Analyze button */}

                <button
                  type="button"
                  className="analyze-button"
                  onClick={() => analyzeImage(selectedFile)}
                  disabled={loading}
                >
                  {loading ? "Analyzing..." : "Analyze Image"}
                </button>

                {/* Backend / analysis error */}

                {analysisError && (
                  <div className="upload-error">
                    {analysisError}
                  </div>
                )}

                {/* Loading state */}

                {loading && <AnalysisLoader />}

                {/* Analysis result */}

                {result && !loading && (
                  <VerdictCard result={result} />
                )}
              </>
            )}
          </div>
        </section>

        {/* =====================================================
            HOW IT WORKS
            ===================================================== */}

        <section
          id="how-it-works"
          className="how-it-works"
        >
          <div className="section-heading">
            <span className="eyebrow">
              HOW IT WORKS
            </span>

            <h2>
              From pixels to forensic evidence.
            </h2>

            <p>
              The system combines visual representations with
              image-level forensic signals before performing
              anomaly detection.
            </p>
          </div>

          <div className="pipeline">
            {/* Step 1 */}

            <div className="pipeline-card">
              <span>01</span>

              <h3>Visual Features</h3>

              <p>
                Foundation-model representations capture
                meaningful visual patterns.
              </p>
            </div>

            <div className="pipeline-arrow">
              →
            </div>

            {/* Step 2 */}

            <div className="pipeline-card">
              <span>02</span>

              <h3>Forensic Analysis</h3>

              <p>
                Frequency, noise, compression and texture
                signals are examined.
              </p>
            </div>

            <div className="pipeline-arrow">
              →
            </div>

            {/* Step 3 */}

            <div className="pipeline-card">
              <span>03</span>

              <h3>Anomaly Detection</h3>

              <p>
                The combined representation is compared with
                patterns learned from real images.
              </p>
            </div>
          </div>
        </section>
      </main>

      {/* =====================================================
          FOOTER
          ===================================================== */}

      <footer id="about">
        <p>
          Zero-Shot AI Image Detector · Research Project
        </p>
      </footer>
    </div>
  );
}

export default App;